name: Bug report
description: Report a bug in lazycommit
labels: [bug, pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file this bug report for lazycommit.
        
        Please provide as much detail as possible to help us reproduce and fix the issue.
  - type: textarea
    attributes:
      label: Bug description
      description: A clear and concise description of the bug.
      placeholder: |
        <!--
          What did you do, what did you expect to happen, and what happened instead?
          
          Example:
          - I ran: lazycommit --type conventional
          - Expected: A conventional commit message to be generated
          - Actual: Got an error "Groq API Error: 400"
        -->
    validations:
      required: true
  - type: input
    attributes:
      label: lazycommit version
      description: |
        Run and paste the output of:
        ```sh
        lazycommit --version
        # or
        npx lazycommit --version
        ```
      placeholder: v1.0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        Please provide step-by-step instructions to reproduce the bug.
      placeholder: |
        1. Set up Groq API key: `lazycommit config set GROQ_API_KEY=your_key`
        2. Stage some files: `git add .`
        3. Run: `lazycommit --type conventional`
        4. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Run and paste the output of:
        ```sh
        npx envinfo --system --binaries --npmPackages
        ```
        
        This information helps us reproduce and debug the issue.
      placeholder: |
        System:
          OS: macOS 14.0
          CPU: arm64
          Shell: zsh
        Binaries:
          Node: 20.0.0
          npm: 10.0.0
        npmPackages:
          lazycommit: 1.0.0
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Groq API Configuration
      description: |
        Please share your Groq API configuration (remove sensitive data):
      placeholder: |
        Model: llama-3.3-70b-versatile
        Type: conventional
        Max length: 50
        Locale: en
    validations:
      required: false
  - type: textarea
    attributes:
      label: Error logs
      description: |
        If there are any error messages, please paste them here.
      placeholder: |
        ```
        Groq API Error: 400 - Error
        400 {"error":{"message":"Invalid model","type":"invalid_request_error"}}
        ```
      render: shell
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Can you contribute a fix?
      description: We would love it if you can open a pull request to fix this bug!
      options:
        - label: I'm interested in opening a pull request for this issue.
        - label: I can help test the fix once it's implemented.
