name: Feature request
description: Suggest an idea for lazycommit
labels: [feature, pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file this feature request for lazycommit.
        
        Please provide as much detail as possible to help us understand and implement your idea.
  - type: textarea
    attributes:
      label: Feature description
      description: A clear and concise description of the feature you would like.
      placeholder: |
        <!--
          What feature would you like to see in lazycommit?
          
          Examples:
          - Support for more AI models (Claude, Gemini, etc.)
          - Custom commit message templates
          - Integration with specific IDEs
          - Batch processing of multiple commits
        -->
    validations:
      required: true
  - type: textarea
    attributes:
      label: Problem/Motivation
      description: |
        Describe the problem you're trying to solve or the motivation behind this feature request.
      placeholder: |
        <!--
          What's the motivation behind this issue?
          
          Examples:
          - "I'm frustrated when I have to manually write commit messages for similar changes"
          - "It would be helpful if lazycommit could understand my project's specific conventions"
          - "I need to generate commit messages in multiple languages for my team"
        -->
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: |
        Describe your proposed solution or how you envision this feature working.
      placeholder: |
        <!--
          How do you think this feature should work?
          
          Examples:
          - "Add a --template flag to specify custom commit message formats"
          - "Support for .lazycommitrc config file with project-specific settings"
          - "Integration with VS Code extension for real-time suggestions"
        -->
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use cases
      description: |
        Describe specific use cases or scenarios where this feature would be helpful.
      placeholder: |
        <!--
          When would you use this feature?
          
          Examples:
          - "When working on a team with specific commit message conventions"
          - "When generating commit messages for different types of projects"
          - "When integrating with CI/CD pipelines"
        -->
    validations:
      required: false
  - type: textarea
    attributes:
      label: Alternatives considered
      description: |
        Have you considered alternative solutions? Is there a workaround?
      placeholder: |
        <!--
          What alternatives have you considered?
          
          Examples:
          - "I could manually write commit messages, but it's time-consuming"
          - "I could use other tools, but they don't integrate as well with my workflow"
          - "I could create custom scripts, but it would be better if it was built-in"
        -->
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Implementation help
      description: |
        Would you like to help implement this feature?
      options:
        - label: I'm interested in implementing this feature myself.
        - label: I can help test this feature once it's implemented.
        - label: I can provide design mockups or detailed specifications.
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Anything else to share? Screenshots? Links? Examples from other tools?
      placeholder: |
        <!--
          Any additional context, examples, or references?
          
          Examples:
          - Screenshots of similar features in other tools
          - Links to related issues or discussions
          - Mockups or wireframes
        -->
    validations:
      required: false
